FROM node:alpine as build

WORKDIR /app
COPY . /app
RUN npm ci

RUN npm run build

FROM nginx:stable

COPY --from=build /app/build /usr/share/nginx/html

RUN rm /etc/nginx/conf.d/default.conf
COPY /public/nginx.conf /etc/nginx/nginx.conf

EXPOSE 80 3000

CMD ["nginx", "-g", "daemon off;"]
