---
galaxy_info:
  author: gelugu
  description: Role description
  company: gelugu
  license: BSD
  min_ansible_version: 1.2
  platforms:
  - name: Ubuntu
    versions:
    - all
  galaxy_tags: [docker]