---

- name: Install NodeJS
  apt: 
    name: nodejs
    state: present 
    update_cache: yes

- name: Install NPM
  apt: 
    name: npm
    state: present 
    update_cache: yes

- name: Install NestJS
  npm:
    name: "{{ item }}"
    state: present
    global: yes
  loop:
    - "@nestjs/cli"
    - "@nestjs/core"
...
