---
- name: Create a teamcity-agent in docker container
  docker_container:
    name: "{{ teamcity_agent_container_name }}"
    image: jacobpeddk/teamcity-agent-nodejs
    user: root
    volumes:
      - "{{ teamcity_agent_local_volume }}:/var/run/docker.sock:ro"
    env:
      SERVER_URL: "http://{{ teamcity_server_host }}:{{ teamcity_server_port }}"
      AGENT_NAME: "{{ teamcity_agent_name }}"
    state: started

