---

- name: Install Docker
  apt: 
    name: docker.io
    state: present 
    update_cache: yes

- name: Install pip
  apt: 
    name: python3-pip
    state: present
    update_cache: yes

- name: Install docker-py
  pip: 
    name: docker-py
    state: present

- name: Start docker service
  service: 
    name: docker
    state: started
    enabled: yes

...