---
- hosts: all
  become: yes
  roles:
    - docker.install

- hosts: teamcity
  become: yes
  roles:
    - teamcity
    - teamcity.agent

- hosts: db
  become: yes
  roles:
    - mongodb

- hosts: node-app
  become: yes
  roles:
    - node.install

- hosts: server
  become: yes
  roles:
    - mern.server

- hosts: client
  become: yes
  roles:
    - nginx

...